macro(source_group_by_dir rootName rootDir)
    if(MSVC)
        foreach (subFile ${ARGN})
            string(REGEX REPLACE ${rootDir}/\(.*\) \\1 filePath ${subFile})
            string(REGEX REPLACE "\(.*\)/.*" \\1 groupName ${filePath})
            string(COMPARE EQUAL ${filePath} ${groupName} noGroup)
            string(REPLACE "/" "\\" groupName ${groupName})
            if(noGroup)
                set(groupName ${rootName})
            else()
                set(groupName ${rootName}/${groupName})
            endif(noGroup)
            source_group(${groupName} FILES ${subFile})
        endforeach (subFile)
        
    endif(MSVC)
endmacro(source_group_by_dir)